"""E2e showcase: reproduce docx_showcase.docx document structure."""
import json
from datetime import UTC, datetime
from pathlib import Path

from mint.create import CreateRequest, create

PROMPT = (
    "Create a professional DOCX Design System & Capabilities Showcase document.\n\n"
    "This document demonstrates EVERY formatting capability of docx-js.\n"
    "Use the showcase guide design system exactly.\n\n"

    "SECTION 1 - COVER PAGE (type=cover, skip_header_footer=true):\n"
    "Title: 'DOCX Generation' (bold, size:72, color:1B3A5C, centered).\n"
    "Subtitle: 'Capabilities Showcase & Design System Guide' (size:28, centered).\n"
    "Description paragraph about comprehensive demonstration (size:22, centered).\n"
    "Version line: 'Version 2.0 - May 2026' (size:20, muted color 666666).\n"
    "Footer line: 'Generated by MINT Runtime - docx-js pipeline' (size:18, muted).\n"
    "Add a thin horizontal line using Paragraph with bottom border "
    "(BorderStyle.SINGLE, size:6, color:2E75B6, space:4).\n\n"

    "SECTION 2 - TABLE OF CONTENTS (type=toc):\n"
    "Heading1: 'Table of Contents'.\n"
    "Add new TableOfContents('TOC', { hyperlink: true, headingStyleRange: '1-3' }).\n\n"

    "SECTION 3 - DESIGN SYSTEM (type=content, level=1):\n"
    "Heading1: '1. Design System'.\n"
    "Paragraph: 'This section defines the foundational design tokens used throughout "
    "all generated documents.'\n\n"

    "Heading2: '1.1 Color Palette'.\n"
    "Paragraph explaining color system with accent color 2E75B6.\n"
    "TABLE (7 columns: Token, Hex, Usage) with rows:\n"
    "  Primary Blue | 1B3A5C | Headings H1, table headers\n"
    "  Accent Blue | 2E75B6 | Headings H2, callout borders, links\n"
    "  Light Blue | D5E8F0 | Dividers, decorative\n"
    "  Success Green | 2E8B57 | Status indicators\n"
    "  Warning Amber | E8A838 | Warning callouts\n"
    "  Error Red | C0392B | Error indicators\n"
    "  Dark Gray | 333333 | Body text\n"
    "  Medium Gray | 666666 | Secondary text\n"
    "  Light Gray | F0F0F0 | Table alt rows\n"
    "Table header: shading fill D5E8F0, bold. Alt rows: fill F0F0F0.\n\n"

    "Info callout: left border (color:2E75B6, size:12, space:8), "
    "shading fill EBF5FB. Bold title 'How it is done' (color:2E75B6), "
    "text explaining color tokens.\n\n"

    "Heading2: '1.2 Typography Scale'.\n"
    "TABLE (5 columns: Style, Font, Size, Weight, Usage) with rows:\n"
    "  Heading 1 | Arial | 16pt (32) | Bold | Section titles\n"
    "  Heading 2 | Arial | 14pt (28) | Bold | Subsections\n"
    "  Heading 3 | Arial | 12pt (24) | Bold | Sub-subsections\n"
    "  Body | Arial | 11pt (22) | Regular | Running text\n"
    "  Caption | Arial | 9pt (18) | Italic | Figure captions\n"
    "  Code | Courier New | 9pt (18) | Regular | Code samples\n"
    "Same table styling.\n\n"

    "Heading2: '1.3 Spacing & Rhythm'.\n"
    "Bullet list (numbering ref 'bullets', level 0) with items:\n"
    "  Heading 1: 360 DXA before + 240 after\n"
    "  Heading 2: 240 DXA before + 180 after\n"
    "  Body text: 120 DXA after\n"
    "  Callout boxes: 200 DXA before + 200 after\n"
    "  Section gap: 400 DXA (~20pt)\n\n"

    "SECTION 4 - TYPOGRAPHY DEMO (type=content, level=1):\n"
    "Heading1: '2. Typography & Character Formatting'.\n"
    "Heading2: '2.1 Character Styles'.\n"
    "Multiple paragraphs demonstrating (each with label TextRun + demo TextRun):\n"
    "  'Bold text:' + bold TextRun\n"
    "  'Italic text:' + italics TextRun\n"
    "  'Underlined:' + underline:{} TextRun\n"
    "  'Strikethrough:' + strike:true TextRun\n"
    "  'Highlighted:' + highlight:'yellow' TextRun\n"
    "  'Colored:' + color:'C0392B' TextRun\n"
    "  'ALL CAPS:' + allCaps:true TextRun\n"
    "  'Small caps:' + smallCaps:true TextRun\n"
    "  'Superscript:' + 'E=mc' + superScript:true '2'\n"
    "  'Subscript:' + 'H' + subScript:true '2' + 'O'\n\n"

    "Info callout explaining TextRun properties.\n\n"

    "Heading2: '2.2 Font Mixing'.\n"
    "Paragraph with multiple TextRuns showing different fonts: Arial, "
    "Times New Roman, Georgia, Courier New.\n\n"

    "Heading2: '2.3 Paragraph Alignment'.\n"
    "4 paragraphs showing AlignmentType.LEFT, CENTER, RIGHT, JUSTIFIED "
    "with descriptive text.\n"
    "Paragraph with indent: { firstLine: 720 } for first-line indent demo.\n"
    "Paragraph with indent: { left: 720 } for block indent demo.\n\n"

    "SECTION 5 - LISTS (type=list, level=1):\n"
    "Heading1: '3. Lists'.\n"
    "Heading2: '3.1 Bulleted List (Multi-level)'.\n"
    "Bullet items using numbering: { reference: 'bullets', level: 0/1/2 }:\n"
    "  Level 0: Primary bullet (3 items)\n"
    "  Level 1: Secondary bullet (2 items, nested under second level-0)\n"
    "  Level 2: Tertiary bullet (1 item, nested)\n\n"

    "Heading2: '3.2 Numbered List'.\n"
    "Numbered items using numbering: { reference: 'numbers', level: 0 }:\n"
    "  3 main items with descriptive text.\n\n"

    "Warning callout about never using manual bullet characters.\n\n"

    "SECTION 6 - TABLES (type=table, level=1):\n"
    "Heading1: '4. Tables'.\n"
    "Heading2: '4.1 Basic Table with Header'.\n"
    "Paragraph explaining table width rules.\n"
    "TABLE (4 columns: Feature, Word, LibreOffice, Google Docs) with rows:\n"
    "  Bold/Italic/Underline | check | check | check\n"
    "  Table cell shading | check | check | check\n"
    "  Multi-level lists | check | check | tilde\n"
    "  Headers & Footers | check | check | check\n"
    "  Embedded images | check | check | check\n"
    "  Table of Contents | check | check | X\n"
    "  Footnotes | check | check | tilde\n"
    "  Multi-column layout | check | check | X\n"
    "Use checkmark symbols (text: 'check', 'tilde', 'X'). "
    "Header row: shading fill 1B3A5C, white bold text. Alt rows.\n\n"

    "Heading2: '4.2 Table with Merged Cells'.\n"
    "TABLE with merged header row (columnSpan:3, fill 1B3A5C, white bold).\n"
    "Data rows: Category | Count | Coverage (3 rows of formatting stats).\n"
    "Alt row shading.\n\n"

    "Info callout about dual width requirement. "
    "Warning callout about WidthType.PERCENTAGE.\n\n"

    "SECTION 7 - CALLOUTS (type=callout, level=1):\n"
    "Heading1: '5. Callout Components'.\n"
    "Paragraph explaining 3 callout variants.\n\n"

    "Heading2: '5.1 Info Callout'.\n"
    "Paragraph with left border (color:2E75B6, size:12, space:8), "
    "shading { fill:'EBF5FB', type:ShadingType.CLEAR }. "
    "Bold blue title 'Info / How it is done' + explanation text.\n\n"

    "Heading2: '5.2 Warning Callout'.\n"
    "Same structure but border color E8A838, shading fill FFF8E1. "
    "Bold amber title 'Warning / Antipattern' + warning text.\n\n"

    "Heading2: '5.3 Code Block'.\n"
    "2 paragraphs with font:'Courier New', size:18, "
    "shading { fill:'F5F5F5', type:ShadingType.CLEAR }, "
    "border all sides (color:'DDDDDD', style:BorderStyle.SINGLE, size:4).\n"
    "Line 1: 'const doc = new Document({ sections: [...] });'\n"
    "Line 2: 'Packer.toBuffer(doc).then(buf => writeFileSync(\\'out.docx\\', buf));'\n\n"

    "SECTION 8 - HYPERLINKS (type=content, level=1):\n"
    "Heading1: '6. Hyperlinks, Bookmarks & Footnotes'.\n"
    "Heading2: '6.1 External Hyperlinks'.\n"
    "Paragraph with ExternalHyperlink to 'https://docs.anthropic.com' "
    "with TextRun text 'Anthropic Documentation' style:'Hyperlink'.\n\n"

    "Heading2: '6.2 Internal Bookmarks'.\n"
    "Create Bookmark with id:'design_system' and TextRun 'Design System'.\n"
    "Add InternalHyperlink with anchor:'design_system', "
    "TextRun 'Design System' style:'Hyperlink'.\n\n"

    "Heading2: '6.3 Footnotes'.\n"
    "Paragraph: 'Document generation uses docx-js library' + "
    "FootnoteReferenceRun(1) + ' with Node.js runtime' + FootnoteReferenceRun(2).\n\n"

    "Heading2: '6.4 Tab Stops'.\n"
    "Paragraph with tabStops: [{ type:TabStopType.RIGHT, "
    "position:TabStopPosition.MAX }]. Children: TextRun 'Left-aligned text' "
    "+ TextRun '\\tRight-aligned on same line'.\n\n"

    "SECTION 9 - PAGE LAYOUT (type=content, level=1, "
    "page_setup with orientation landscape):\n"
    "Heading1: '7. Page Layout'.\n"
    "Paragraph explaining this page uses landscape via section break.\n"
    "TABLE (9 columns: Feature, Word Win, Word Mac, Word Web, "
    "LibreOffice, Google Docs, Pages, WPS, OnlyOffice, PDF) with 8 rows "
    "showing compatibility matrix. Header: 1B3A5C background, white bold. "
    "Alt rows. Width: 12960 DXA (landscape content width).\n\n"

    "SECTION 10 - MULTI-COLUMN (type=content, level=1, "
    "page_setup with columns count:2, space:720, separate:true):\n"
    "Heading1: '8. Multi-Column Layout'.\n"
    "Paragraph explaining column layout.\n"
    "3-4 paragraphs about column configuration, unequal columns, "
    "SectionType.NEXT_COLUMN, and key limitations.\n\n"

    "SECTION 11 - API REFERENCE (type=appendix, level=1):\n"
    "Heading1: 'Appendix: API Quick Reference'.\n"
    "Paragraph about complete feature-to-API mapping.\n"
    "TABLE (3 columns: Feature, API, Notes) with 16+ rows covering:\n"
    "  Bold, Italic, Color, Font, Size, Heading, Alignment, Indent, "
    "  Spacing, Bullet list, Table, Cell shade, Cell merge, Image, "
    "  Page break, Section, Landscape, Columns, Header, Footer, "
    "  TOC, Hyperlink, Bookmark, Footnote, Tab stop, Border, Shading.\n"
    "Header: 1B3A5C bg, white bold. Alt rows.\n\n"

    "Final paragraph: bold 'End of Document', then "
    "'Generated by MINT Runtime - May 2026'.\n\n"

    "DOCUMENT-LEVEL CONFIG:\n"
    "footnotes: { 1: { children: [Paragraph('docx-js: github.com/dolanmiu/docx')] }, "
    "  2: { children: [Paragraph('Node.js v18+ runtime required')] } }\n"
    "numbering config: 'bullets' (3 levels: BULLET) and 'numbers' "
    "(3 levels: DECIMAL, LOWER_LETTER, LOWER_ROMAN)\n"
    "header: 'DOCX Showcase' left + PositionalTab right + 'MINT Runtime'\n"
    "footer: 'MINT Runtime' + PositionalTab + "
    "PageNumber.CURRENT + ' / ' + PageNumber.TOTAL_PAGES\n\n"

    "CRITICAL RULES:\n"
    "- Font sizes in HALF-POINTS: 11pt=22, 14pt=28, 16pt=32, 36pt=72. NEVER above 100.\n"
    "- Use heading: HeadingLevel.HEADING_1/2/3 for headings.\n"
    "- Table width: {size:9360, type:WidthType.DXA} for portrait, "
    "{size:12960} for landscape. columnWidths must sum to total.\n"
    "- Cell width: {size:N, type:WidthType.DXA}. Cell margins: "
    "{top:80,bottom:80,left:120,right:120}.\n"
    "- Shading: always {fill:'HEX', type:ShadingType.CLEAR}. NEVER type:'solid'.\n"
    "- Separate ALL elements with commas.\n"
    "- No import/require/fs. All docx-js classes are pre-loaded.\n"
)

PRIMARY_MODEL = "qwen3.6:35b"
FALLBACK_MODEL = "glm-4.7-flash:latest"
BASE_URL = "http://10.128.26.10:11434/v1"

req = CreateRequest(
    format="docx",
    tier="frontier",
    prompt=PROMPT,
    modular=True,
    llm_base_url=BASE_URL,
    llm_model=PRIMARY_MODEL,
    llm_fallback_model=FALLBACK_MODEL,
)

result = create(req, rules_dir=Path("rules"))

print(f"\n{'='*60}")
print("  MINT Showcase Guide Generation Report")
print(f"  {datetime.now(UTC).isoformat()[:19]}")
print(f"{'='*60}")
print(f"  Success:    {result.success}")
print(f"  Mode:       {result.execution_mode}")
print(f"  Output:     {result.output_path}")
print(f"  Duration:   {result.duration_ms / 1000:.1f}s")
print(f"  Sections:   {result.sections_succeeded}/{result.sections_total} succeeded")

if result.error:
    print(f"  Error:      {result.error[:200]}")

if result.validation_report:
    hard = [v for v in result.validation_report.violations if v.severity.value == "hard"]
    soft = [v for v in result.validation_report.violations if v.severity.value == "soft"]
    print(f"  Validation: hard={len(hard)}, soft={len(soft)}")

if result.section_details:
    print(f"\n  {'─'*56}")
    print(f"  {'Section':<25} {'Model':<20} {'Att':>3} {'Ms':>6} {'Chars':>6} {'OK':>3}")
    print(f"  {'─'*56}")
    models_used: dict[str, dict[str, int]] = {}
    for d in result.section_details:
        sid = d["section_id"][:24]
        model_short = d["model"].split(":")[0][:19]
        ok = "Y" if d["success"] else "N"
        print(
            f"  {sid:<25} {model_short:<20} "
            f"{d['attempt']:>3} {d['duration_ms']:>6} {d['code_chars']:>6} {ok:>3}"
        )
        key = d["model"]
        if key not in models_used:
            models_used[key] = {"count": 0, "success": 0, "total_ms": 0, "total_chars": 0}
        models_used[key]["count"] += 1
        if d["success"]:
            models_used[key]["success"] += 1
        models_used[key]["total_ms"] += d["duration_ms"]
        models_used[key]["total_chars"] += d["code_chars"]

    print("\n  Model Summary:")
    for model, stats in models_used.items():
        print(
            f"    {model}: {stats['success']}/{stats['count']} success, "
            f"{stats['total_ms']/1000:.1f}s total, "
            f"{stats['total_chars']} chars generated"
        )

if result.plan:
    print("\n  Plan Sections:")
    for s in result.plan.sections:
        ps_info = ""
        if s.page_setup:
            if s.page_setup.orientation == "landscape":
                ps_info += " [LANDSCAPE]"
            if s.page_setup.columns and s.page_setup.columns.count > 1:
                ps_info += f" [{s.page_setup.columns.count}col]"
        print(f"    [{s.type}] {s.title} (level={s.level}){ps_info}")

report = {
    "timestamp": datetime.now(UTC).isoformat(),
    "primary_model": PRIMARY_MODEL,
    "fallback_model": FALLBACK_MODEL,
    "success": result.success,
    "execution_mode": result.execution_mode,
    "duration_s": result.duration_ms / 1000,
    "sections_total": result.sections_total,
    "sections_succeeded": result.sections_succeeded,
    "section_details": result.section_details,
    "output_path": str(result.output_path) if result.output_path else None,
    "error": result.error,
}

report_name = f"showcase_guide_report_{datetime.now(UTC).strftime('%Y%m%d_%H%M%S')}.json"
report_path = Path("e2e_results") / report_name
report_path.parent.mkdir(exist_ok=True)
report_path.write_text(json.dumps(report, indent=2))
print(f"\n  Report saved: {report_path}")
